cadastro/urls.py
from django.urls import path
from cadastro import views

app_name = 'cadastro'

urlpatterns = [
    path("signup/", views.signup, name = 'signup'),
    path("login/", views.login, name = 'login'),
    path("", views.index, name = 'index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from cadastro import urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('cadastro.urls')),
]

cadastro/models.py
from django.db import models

# Create your models here.

cadastro/models/cadastro_usuario.py
from django.db import models
from django.utils import timezone

class Departamento(models.Model):
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome
    

class Pessoa(models.Model):
    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    MEDICO = 'MED'
    PACIENTE = 'PAC'

    USUARIOS_CHOICES = [
        (MEDICO, 'medico'),
        (PACIENTE, 'paciente')
    ]
    
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    data_nascimento = models.DateField(auto_now=False)
    cpf = models.CharField(max_length=11, unique=True)
    rg = models.CharField(max_length=10, unique=True)
    email = models.EmailField(max_length=128)
    crm = models.CharField(max_length=13, unique=True, blank=True)
    show = models.BooleanField(default=True)
    usuario = models.CharField(max_length=3, choices=USUARIOS_CHOICES, default=PACIENTE)
    data_cadastro = models.DateTimeField(default=timezone.now)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, default='Paciente')

    def __str__(self) -> str:
        return f'{self.nome} {self.sobrenome}'

cadastro/models/model_credencial.py
from django.db import models
from .model_pessoa import Pessoa

class Credencial(models.Model):
    class Meta:
        verbose_name= "Credencial"
        verbose_name_plural= "Credenciais"

    registro = models.CharField(max_length=12 , unique=True)
    data_de_inscricao = models.DateField(auto_now=False)
    especialidade = models.CharField(max_length=50)
    situacao = models.CharField(max_length=10)
    id_pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, blank=True)

    def __str__(self) -> str:
        return f'{self.regitro} {self.especialidade} {self.situacao} {self.id_pessoa}'

cadastro/models/model_departamento.py
from django.db import models

class Departamento(models.Model):
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome
    

cadastro/models/model_endereco.py
from django.db import models
from .model_pessoa import Pessoa

class Endereco(models.Model):
    class Meta:
        verbose_name = 'Endereco'
        verbose_name_plural = 'Enderecos'

    rua = models.CharField(max_length=30, blank=True)
    numero = models.CharField(max_length=5, blank=True)
    bairro = models.CharField(max_length=30, blank=True)
    cidade = models.CharField(max_length=30, blank=True)
    uf = models.CharField(max_length=2, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    id_pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, blank=True)

    def __str__(self) -> str:
        return f'{self.cidade} {self.uf} {self.id_pessoa}'

cadastro/models/model_pessoa.py
from django.db import models
from .model_departamento import Departamento
from django.utils import timezone



class Pessoa(models.Model):
    class Meta:
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'


    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    data_nascimento = models.DateField(auto_now=False)
    cpf = models.CharField(max_length=11, unique=True)
    rg = models.CharField(max_length=10, unique=True)
    email = models.EmailField(max_length=128, unique=True)
    show = models.BooleanField(default=True)
    data_cadastro = models.DateTimeField(default=timezone.now)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, default='Paciente')

    def __str__(self) -> str:
        return f'{self.nome} {self.sobrenome}'

cadastro/models/model_prontuario.py
from django.db import models
from .model_pessoa import Pessoa
from django.contrib.auth.models import User
from django.utils import timezone


class Prontuario(models.Model):
    class Meta:
        verbose_name = 'Prontuarios'
        verbose_name_plural = 'Prontuarios'

    arquivo = models.FileField(blank=True)
    data_criacao = models.DateTimeField(default=timezone.now)
    id_pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, blank=True)
    proprietario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.proprietario} {self.data_criacao}'

cadastro/models/model_telefone.py
from django.db import models
from .model_pessoa import Pessoa

class Telefone(models.Model):
    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

    numero = models.CharField(max_length=15)
    tipo = models.CharField(max_length=10)
    id_pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, blank=True)

    def __str__(self) -> str:
        return f'{self.numero} {self.tipo}'
    

cadastro/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'cadastro/index.html')

cadastro/views/index.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http.response import HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_dj



def index(request):
    if request.user.is_authenticated:
        return render(request, 'cadastro/index.html')
    
    return render(request, 'cadastro/login.html')

def login(request):
    if request.method == "GET":
        return render(request, 'cadastro/login.html')
    else:
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user = authenticate(request, username=email, password=senha)

        if user:
            login_dj(request, user)
            return render(request, 'cadastro/index.html')
        else:
            return HttpResponse('email ou senha invalido')

def signup(request):
    if request.method == "GET":
        return render(request, 'cadastro/signup.html')
    else:
        nome = request.POST.get('nome')
        sobrenome = request.POST.get('sobrenome')
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user_checked = User.objects.filter(email=email)

        if user_checked:
            return HttpResponse("usuario ja cadastrado")
        
        user = User.objects.create_user(username=email, first_name=nome, last_name=sobrenome, email=email, password=senha)
        user.save()

        return HttpResponse('Usuario cadastrado com sucesso')

cadastro/templates/cadastro/index.html
{% extends 'global/base.html' %}

{% block content %}
    <h1>Index</h1>
{% endblock content %}

cadastro/templates/cadastro/login.html
{% extends 'global/base.html' %}

{% block content %}
    <div id="formulario" class="login">
        <form action="{% url 'cadastro:login' %}" method="POST">
            {% csrf_token %}
            <h2>Login</h2>
            <label for="email">
                <input type="email" name="email" id="email" placeholder="E-mail" class="input">
            </label>
            <label for="password">
                <input type="password" name="senha" id="pass" placeholder="Senha" class="input">
            </label>
            <input type="submit" value="Entrar" class="btn">
            <p class="link"><a href="#">Esqueceu sua Senha?</a></p>
            <button class="btn"><a href="{% url 'cadastro:signup' %}" class="btna">Cadastre-se</a></button>
        </form>
    </div>
{% endblock content %}

cadastro/templates/cadastro/signup.html
{% extends "global/base.html" %}

{% block content %}

    <div id="formulario" class="login">    
        <form action="{% url 'cadastro:signup' %}" method="POST">
            {% csrf_token %}
            <h2>Cadastro</h2>
            <label for="name">
                <input type="text" name="nome" id="name" placeholder="Nome" class="input">
            </label>
            <label for="sobrenome">
                <input type="text" name="sobrenome" id="sobrenome" placeholder="Sobrenome" class="input">
            </label>
            <label for="email">
                <input type="email" name="email" id="email" placeholder="E-mail" class="input">
            </label>
            <label for="password">
                <input type="password" name="senha" id="pass" placeholder="Senha" class="input">
            </label>

            <span class="valido"></span>
            <input type="submit" value="Cadastrar" class="btn" name="Cadastre-se">
            <button class="btn"><a href="{% url 'cadastro:login' %}" class="btna">Entrar</a></button>
        </form>
    </div>
{% endblock content %}